# Config file for automatic testing at travis-ci.org
arch:
 - amd64
 - ppc64le
sudo: false
language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"

env:
- PYTEST=3
- PYTEST=4
- PYTEST=5
- PYTEST=master

matrix:
  include:
    - python: 'pypy'
      dist: trusty
      env: PYTEST=4
    - python: 2.7
      env: PYTEST=3
    - python: 2.7
      env: PYTEST=4
    - python: 3.4
      env: PYTEST=3
    - python: 3.4
      env: PYTEST=4
    - python: 3.8
      arch: ppc64le
      env: PYTEST=3
    - python: 3.8
      arch: ppc64le
      env: PYTEST=4
  exclude:
     - arch : ppc64le
       python : 3.5
     - arch : ppc64le
       python : pypy3	
     - arch : ppc64le
       python : 3.6
jobs:
  allow_failures:
    - env: PYTEST=master

install:
  - "[[ $TRAVIS_PYTHON_VERSION == pypy ]] || pip install coveralls"
  - pip install tox-travis coverage
script:
  - tox -v
  - coverage combine
after_success:
  - "[[ $TRAVIS_PYTHON_VERSION == pypy ]] || COVERALLS_PARALLEL=true coveralls"

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
